version: "3.8"

services:
  xsolla-sdk-php:
    image: ghcr.io/newztech/xsolla-sdk-php:latest
    container_name: xsolla-sdk-php
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9000:9000"
    networks:
      - xsolla-network

networks:
  xsolla-network:
    driver: bridge