version: "3.8"

services:
  xsolla-sdk-php:
    image: xsolla-sdk-php
    container_name: xsolla-sdk-php
    build:
      context: .
      args:
        PHP_VERSION: "7.3"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3